# Generated by Django 4.2.4 on 2023-08-20 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0006_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='статус подписки')),
                ('version', models.CharField(default=1, max_length=100, verbose_name='версия подписки')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.course', verbose_name='курс')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на курс',
                'verbose_name_plural': 'Подписки на курсы',
                'ordering': ('owner', 'course'),
            },
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
